import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart' show kIsWeb;
import 'package:provider/provider.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_database/firebase_database.dart';
import 'package:package_info_plus/package_info_plus.dart';
import 'firebase_options.dart'; // generated by `flutterfire configure` — see setup guide
import 'services/firebase_service.dart';
import 'state/app_state.dart';
import 'auth_gate.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'services/push_notification_service.dart';
import 'package:flutter/services.dart';

// Must match DEVICE_ID in your ESP32 firmware exactly.
const String kDeviceId = 'dispenser_01';

// The app's version, read from pubspec.yaml's `version:` field at
// launch (see main() below) — About and the side menu footer both
// read this directly instead of hardcoding a version string.
late PackageInfo appPackageInfo;

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await SystemChrome.setEnabledSystemUIMode(SystemUiMode.edgeToEdge);

  // Must complete before runApp() — About and the side menu footer
  // read appPackageInfo synchronously rather than via a FutureBuilder.
  appPackageInfo = await PackageInfo.fromPlatform();

  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  FirebaseMessaging.onBackgroundMessage(firebaseMessagingBackgroundHandler);

  // Realtime Database does NOT cache data to disk by default — without
  // this, going offline means the app has nothing to show at all (the
  // empty-dashboard bug), because .onValue simply never fires until a
  // connection exists. This makes the last-synced data available
  // immediately, even offline. Must be called before any DatabaseReference
  // is used, and only once per app run.
  //
  // Not supported on Flutter web — the browser's IndexedDB caching is
  // handled internally by the Firebase JS SDK instead, so this call
  // would throw there.
  if (!kIsWeb) {
    FirebaseDatabase.instance.setPersistenceEnabled(true);
  }

  runApp(
    ChangeNotifierProvider(
      create: (_) => AppState(FirebaseService(kDeviceId)),
      // lazy: false — without this, Provider doesn't actually call
      // create() until something first does context.watch<AppState>()
      // or context.read<AppState>(). The first real consumer is
      // _Shell in app_root.dart, which only mounts AFTER sign-in
      // (LoginScreen and AuthGate deliberately avoid Provider — see
      // their own comments). That means AppState's constructor — and
      // the notifications.initPlatform() call inside it, which is
      // what actually requests the OS notification permission — was
      // firing at first SIGN-IN, not at fresh install/first launch as
      // intended. lazy: false forces AppState to construct right here,
      // immediately, so the permission prompt fires before LoginScreen
      // is even shown.
      lazy: false,
      child: MaterialApp(
        title: 'MedCare IoT',
        debugShowCheckedModeBanner: false,
        theme: ThemeData(useMaterial3: true, fontFamily: 'Roboto'),
        home: AuthGate(key: AuthGate.authGateKey), // <-- changed
      ),
    ),
  );
}