import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart' show kIsWeb;
import 'package:provider/provider.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_database/firebase_database.dart';
import 'firebase_options.dart'; // generated by `flutterfire configure` — see setup guide
import 'services/firebase_service.dart';
import 'state/app_state.dart';
import 'auth_gate.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'services/push_notification_service.dart';
import 'package:flutter/services.dart';

// Must match DEVICE_ID in your ESP32 firmware exactly.
const String kDeviceId = 'dispenser_01';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await SystemChrome.setEnabledSystemUIMode(SystemUiMode.edgeToEdge);
  
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  FirebaseMessaging.onBackgroundMessage(firebaseMessagingBackgroundHandler);

  // Realtime Database does NOT cache data to disk by default — without
  // this, going offline means the app has nothing to show at all (the
  // empty-dashboard bug), because .onValue simply never fires until a
  // connection exists. This makes the last-synced data available
  // immediately, even offline. Must be called before any DatabaseReference
  // is used, and only once per app run.
  //
  // Not supported on Flutter web — the browser's IndexedDB caching is
  // handled internally by the Firebase JS SDK instead, so this call
  // would throw there.
  if (!kIsWeb) {
    FirebaseDatabase.instance.setPersistenceEnabled(true);
  }

  runApp(
    ChangeNotifierProvider(
      create: (_) => AppState(FirebaseService(kDeviceId)),
      child: MaterialApp(
        title: 'MedCare IoT',
        debugShowCheckedModeBanner: false,
        theme: ThemeData(useMaterial3: true, fontFamily: 'Roboto'),
        home: AuthGate(key: AuthGate.authGateKey), // <-- changed
      ),
    ),
  );
}